-- Create the food_cost_logs table
create table public.food_cost_logs (
  id bigint generated by default as identity primary key,
  outlet_id text not null,
  value numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.food_cost_logs enable row level security;

-- Create a policy that allows all operations for now (can be restricted later)
create policy "Enable all access for all users"
on public.food_cost_logs
for all
using (true)
with check (true);

-- Create the mila_suggestions table
create table public.mila_suggestions (
  id bigint generated by default as identity primary key,
  user_name text not null,
  outlet_code text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for mila_suggestions
alter table public.mila_suggestions enable row level security;

-- Allow all access (for now)
create policy "Enable all access for suggestions"
on public.mila_suggestions
for all
using (true)
with check (true);


-- Create outlets table
create table public.outlets (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  code text not null unique,
  color_hex text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for outlets
alter table public.outlets enable row level security;

-- Allow read access for all users
create policy "Enable read access for all users"
on public.outlets
for select
using (true);

-- Insert Seed Data
insert into public.outlets (name, code, color_hex) values
  ('Royal', 'ROY02', '#FFD700'),     -- Gold
  ('Fisher''s', 'FISH01', '#00BFFF'), -- Deep Sky Blue
  ('Ralph''s', 'RAL03', '#32CD32'),   -- Lime Green
  ('Gusto', 'GUS04', '#FF4500');      -- Orange Red
