-- 1. Bases: Outlets & Actions
create table if not exists public.outlets (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  code text not null unique,
  location text,
  color_hex text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Migration: Add location column if it doesn't exist
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name='outlets' and column_name='location') then
    alter table public.outlets add column location text;
  end if;
end $$;

alter table public.outlets enable row level security;
drop policy if exists "Enable read access for all" on public.outlets;
create policy "Enable read access for all" on public.outlets for select using (true);
drop policy if exists "Enable all access for all" on public.outlets;
create policy "Enable all access for all" on public.outlets for all using (true) with check (true);

insert into public.outlets (name, code, location, color_hex) values
  ('Royal', 'ROY02', 'Bangkok', '#FF914D'),   -- Orange
  ('Fisher''s', 'FISH01', 'Phuket', '#C8A413'), -- Gold
  ('Ralph''s', 'RAL03', 'Chiang Mai', '#77B139'),   -- Green
  ('Gusto', 'GUS04', 'Samui', '#718096')       -- Grey
on conflict (code) do update set color_hex = excluded.color_hex, name = excluded.name, location = excluded.location;

create table if not exists public.gamification_actions (
  id uuid default gen_random_uuid() primary key,
  display_name text not null unique,
  points_value integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.gamification_actions enable row level security;
drop policy if exists "Enable read for all" on public.gamification_actions;
create policy "Enable read for all" on public.gamification_actions for select using (true);
drop policy if exists "Enable all for all" on public.gamification_actions;
create policy "Enable all for all" on public.gamification_actions for all using (true) with check (true);

insert into public.gamification_actions (display_name, points_value) values
  ('Standard Check-in', 10),
  ('Inventory Update', 25),
  ('Waste Report Submitted', 50),
  ('Daily Goal Met', 100)
on conflict (display_name) do update set points_value = excluded.points_value;

-- 2. Profiles (Strict: full_name, outlet_id)
create table if not exists public.profiles (
  id uuid default gen_random_uuid() primary key,
  full_name text not null unique,
  outlet_id uuid references public.outlets(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;
drop policy if exists "Profiles read access" on public.profiles;
create policy "Profiles read access" on public.profiles for select using (true);
drop policy if exists "Profiles write access" on public.profiles;
create policy "Profiles write access" on public.profiles for all using (true) with check (true);

-- 3. Ledger (Strict: profile_id)
create table if not exists public.gamification_ledger (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id),
  action_id uuid references public.gamification_actions(id),
  profile_id uuid references public.profiles(id),
  points_awarded integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.gamification_ledger enable row level security;
drop policy if exists "Ledger read access" on public.gamification_ledger;
create policy "Ledger read access" on public.gamification_ledger for select using (true);
drop policy if exists "Ledger write access" on public.gamification_ledger;
create policy "Ledger write access" on public.gamification_ledger for all using (true) with check (true);

-- 4. Views (Leaderboard & Logs)
create or replace view public.outlet_engagement_overview as
select 
  o.id as id,
  o.name as name,
  o.color_hex as outlet_color,
  coalesce(sum(gl.points_awarded), 0) as total_points,
  round(coalesce(sum(gl.points_awarded), 0) * 100.0 / 3000.0, 1) as engagement_pct
from public.outlets o
left join public.gamification_ledger gl on o.id = gl.outlet_id
group by o.id, o.name, o.color_hex;

create or replace view public.staff_leaderboard_display as
select 
  p.id as id,
  p.full_name as name,
  o.name as outlet_name,
  o.color_hex as outlet_dot_color,
  coalesce(sum(gl.points_awarded), 0) as total_points
from public.profiles p
join public.outlets o on p.outlet_id = o.id
left join public.gamification_ledger gl on p.id = gl.profile_id
group by p.id, p.full_name, o.name, o.color_hex;

create or replace view public.gamification_recent_logs as
select 
  gl.id,
  gl.points_awarded,
  gl.created_at,
  ga.display_name as action_name,
  p.full_name as staff_name,
  o.name as outlet_name
from public.gamification_ledger gl
join public.gamification_actions ga on gl.action_id = ga.id
left join public.profiles p on gl.profile_id = p.id
join public.outlets o on gl.outlet_id = o.id
order by gl.created_at desc
limit 20;

-- 5. Final Permissions
grant all on public.outlets to authenticated, anon;
grant all on public.gamification_actions to authenticated, anon;
grant all on public.profiles to authenticated, anon;
grant all on public.gamification_ledger to authenticated, anon;
grant select on public.outlet_engagement_overview to authenticated, anon;
grant select on public.staff_leaderboard_display to authenticated, anon;
grant select on public.gamification_recent_logs to authenticated, anon;
